<p>Prequalify your self with slope payment.</p>
<button class="action-primary slope slope-prequalify-btn" id="slope-prequalify">
    <span>
        <img src="<?= /* @noEscape */ $block->getViewFileUrl('Alfakher_SlopePayment::images/slope_logo_white.png'); ?>"
            alt="Slope Logo" style="height: 12px;"> Pre Qualify with Slope</span>
</button>
<script type="text/x-magento-init">
    {
        "*": {
            "Alfakher_SlopePayment/js/view/customer/slope-prequalify" : {
            }
        }
    }
</script>
