stage:
  global:
    SKIP_HTML_MINIFICATION: true
  build:
    SKIP_SCD: false
  deploy:
    SEARCH_CONFIGURATION:
      engine: elasticsearch7
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    MYSQL_USE_SLAVE_CONNECTION: true
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: []