stage:
  global:
    SKIP_HTML_MINIFICATION: true
  build:
    SKIP_SCD: false
    SCD_STRATEGY: "compact"
  deploy:
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: true
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: [ ]
