stage:
  global:
    SKIP_HTML_MINIFICATION: true
  build:
    SKIP_SCD: false
    QUALITY_PATCHES:
      - MDVA-40311
      - MDVA-41628
      - MDVA-42507
      - MDVA-38447
      - MDVA-43824
      - ACSD-45143
  deploy:
    SEARCH_CONFIGURATION:
      engine: elasticsearch7
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: true
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\Redis'
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: [ ]
