stage:
  global:
    SKIP_HTML_MINIFICATION: true
  deploy:
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: true
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\Redis'
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: [ ]
