<?php
/*Get Current Category*/
$category = $block->getCurrentCategory();
$subcats = $category->getChildrenCategories();
?>

<div class="site-container category_title">
    <h1 class="cat_tite"><?= /* @noEscape */ $category->getName(); ?></h1>
</div>
<!-- this condition to check wether sub category exists[BS]start -->
<?php $arrow = "false"; ?>
<?php if ($subcats->getSize() >= 7):
         $arrow = "true";
      endif; ?>
<?php if (!empty($subcats->getData())): ?>
    <div class="shorting_main">

        <div class="shorting_slider">
           <?php foreach ($subcats as $subcat): ?>
                <?php if ($subcat->getIsActive()): ?>
                    <?php $subcaturl = $subcat->getUrl(); ?>
                    <div class="shorting_title">
                        <a href="<?= /* @noEscape */ $subcaturl?>"><?= /* @noEscape */ $subcat->getName();?></a>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<!-- condition to check wether sub category exists[BS]end -->


<script>
    require([
        "jquery",
        "Magento_PageBuilder/js/resource/slick/slick",
        "domReady!"
    ], function ($) {
                if (<?= /* @noEscape */ $arrow ?> == true ) {
                 $('.shorting_slider').slick({
                    dots: false,
                    arrows: true,
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    autoplay: false,
                    infinite: true,
                    variableWidth: true
                });
             }
    });
</script>