<?php
/*Get Current Category*/
$category = $block->getCurrentCategory();
$subcats = $category->getChildrenCategories();
?>

<div class="site-container category_title">
    <!-- <div class="category_title"> -->
        <h2 class="cat_tite"><?php echo $category->getName(); ?></h2>
    <!-- </div> -->
</div>
<div class="shorting_main">
    <div class="shorting_slider">
        <?php
        foreach ($subcats as $subcat):
            $_category = $block->getChildCategory($subcat->getId());
            $subcaturl = $subcat->getUrl();?>
            <div class="shorting_title"><a href="<?= $subcaturl?>"><?= $subcat->getName();?></a></div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_PageBuilder/js/resource/slick/slick",
        "domReady!"
    ], function ($) {
        $(window).load(function() {
             setTimeout(function () {
                 $('.shorting_slider').slick({
                    dots: false,
                    arrows: true,
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    autoplay: false,
                    infinite: true,
                    variableWidth: true,
                });
            }, 0);
        });
    });
</script>