<!-- Yasin Document verification msg Start -->

<?php
    //system config value 
    $config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
    $documents_required_msg = $config->getConfigValue('hookahshisha/productpage/productpageb2b_documents_verification_required');
    $document_Verification_msg = $config->getConfigValue('hookahshisha/productpage/productpageb2b_document_Verification_section');
    $document_Reject_msg = $config->getConfigValue('hookahshisha/productpage/productpageb2b_document_rejection_sections');
    $document_expir_msg = $config->getConfigValue('hookahshisha/productpage/productpageb2b_documents_expired_sections');

    $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class);
    $docdata = $_helperB2b->getDocMessageData();
    $exp_msg = $_helperB2b->getExpiryMsg();
    $is_document_upload = $_helperB2b->getDocuments();
?>
<?php if($_helperB2b->isCustomerLoggedIn()): ?>
    <?php if ($docdata == 0): ?>
        <div class="pending-tooltip"><div class="tooltip-inner"><?= $block->escapeHtml(__($document_Verification_msg)) ?></div>
        </div>
     
    <?php elseif ($docdata == 1): ?>
        <div class="pending-tooltip"><div class="tooltip-inner"><?= $block->escapeHtml(__($document_Reject_msg)) ?></div></div>
    <?php endif; ?>

    <?php if ($exp_msg == 0): ?>
        <div class="pending-tooltip exp"><div class="tooltip-inner"><?= $block->escapeHtml(__($document_expir_msg)) ?></div></div>
    <?php endif; ?>
    
    <?php if ($is_document_upload == 0): ?>
        <div class="pending-tooltip"><div class="tooltip-inner"><?= $block->escapeHtml(__($documents_required_msg)) ?></div></div>
    <?php endif; ?>
<?php endif; ?>    

<!--Yasin Document verification msg End -->