<?php
$helper = $this->helper('HookahShisha\ChangePassword\Helper\Data'); 
$helperb2b = $this->helper(\Alfakher\Productpageb2b\Helper\Data::class);
$yotpotab = $helperb2b->getConfigValue('yotpo_loyalty/advanced/enable_yotpo_tab');
?>
<?php if($yotpotab==1): ?>
<div class="my_rewards">
    <?php if($helper->customerLoggedIn()): ?>
        <a class= "header_account_link" href="<?php echo $this->getUrl("custom/customer/yotpo");?>"><?php echo __('My Rewards')?></a>
    <?php else: ?>
        <a class= "header_account_link" href="<?php echo $this->getUrl("customer/account/login");?>"><?php echo __('My Rewards')?></a>
    <?php endif; ?>
</div>
<?php endif; ?>