<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
 <?php 
   $helper = $this->helper('HookahShisha\CheckCustomerLogin\Helper\Data');
   $values = $helper->CustomerLogin();
   if($values == true){?>
     <a class= "header_account_link" href="<?php echo $this->getUrl("customer/account/logout");?>"><?php echo __('My Account')?></a><?php
   }else{?>
     <div class="sign-in">
     <!--  <a class= "header_account_link" href="<?php //echo $this->getUrl("customer/account/login");?>"><?php //echo __('Sign in')?></a> -->
     <span class="sign-up"><?php echo __('Sign in/Sign Up')?></span>
        <ul class="sign-up-ul" style="display: none;">
           <li>Weclome Guest</li>
           <li><a class= "sign_in_link" href="<?php echo $this->getUrl("customer/account/login");?>"><?php echo __('Sign in')?></a></li>
           <li><a class= "create_an_account_link" href="<?php echo $this->getUrl("customer/account/create");?>"><?php echo __('Sign Up')?></a></li>
        </ul>
     </div>
      <?php
   }

?>
<script>
require(['jquery'], function($){
    $(document).ready(function(){
        $('.sign-up').click(function(){
             $('.sign-up-ul').toggle();
        });
    });
});
</script>