<?php $helper = $this->helper('HookahShisha\ChangePassword\Helper\Data'); ?>
<div class="reorder-wrapper">
    <?php if($helper->customerLoggedIn()): ?>
        <a class= "header_account_link" href="<?php echo $this->getUrl("sales/order/history");?>"><?= $block->escapeHtml(__('my orders')) ?></a>
    <?php else: ?>
        <a class= "header_account_link" href="<?php echo $this->getUrl("customer/account/login");?>"><?= $block->escapeHtml(__('my orders')) ?></a>
    <?php endif; ?>
</div>