<?php
$category = $block->getCurrentCategory();
$subcats = $category->getChildrenCategories();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$imageHelper = $this->helper(\Magento\Catalog\Helper\Image::class);
$placeholderImageUrl = $imageHelper->getDefaultPlaceholderUrl('image');

?>

<!-- Show child category image and name start[BS] -->
<div class="block-content content">
<div class="products wrapper grid products-grid products">
<div class="column main">

<div class="products list items product-items">
<?php
foreach ($subcats as $subcat):
    if ($subcat->getIsActive()):
            $_category = $block->getChildCategory($subcat->getId());
            $_outputhelper = $this->helper(Magento\Catalog\Helper\Output::class);
            $subcaturl = $subcat->getUrl();
            $_imgHtml = '';
            $_imgUrl = $_category->getImageUrl();
            $_disc = $_category->getCategoryDesc();
        if ($_imgUrl) {
            $_imgHtml = '<img class="cateshop_img" src="' . $_imgUrl . '" height="300" width="300" alt="Product" />';
        } else {
            $_imgHtml = '<img class="cateshop_img" src="' . $placeholderImageUrl . '" height="300" width="300" alt="Product" />';
        }
            $_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');

        ?>

            <div class="item product product-item">
                <div class="product-item-info">
                        <a href="<?= /* @noEscape */ $subcaturl ?>" class="product photo product-item-photo">
                            <?= /* @noEscape */ $_imgHtml ?>
                        </a>
                    <div class="product details product-item-details">                        
                        <strong class="product name product-item-name"><a
                                class="product-item-link"
                                title="<?= /* @noEscape */ $subcat->getName() ?>"
                                href="<?= /* @noEscape */ $subcaturl ?>">
                            <?= /* @noEscape */ $subcat->getName() ?></a>
                        </strong>
                        <div class="catalog description-item">
                            <?= /* @noEscape */ $_disc; ?>
                        </div>
                    </div>
                </div>
            </div>

   <?php  endif;
endforeach;
?>
</div>
</div>
</div>
</div>

<!-- Show child category image and name start[BS] -->


<script>
    require(['jquery'], function ($) {
        $(".toolbar-products").hide();
        $(".amscroll-load-button").hide();
        $(".amscroll-load-button" ).remove();
    });
</script>

