<?php 
$paymentarray=$block->getPaymentarray();
?>

<table border="1">
	<thead>
		<tr>
			<th>Payment Type</th>
			<th>Transaction Number</th>
			<th>Amount Paid</th>
			<th>Date</th>
		</tr>
	</thead>
	<?php if(!empty($paymentarray)): ?>
		<tbody>
		<?php foreach ($paymentarray as $key => $value): ?>
			<tr>
				<td><?= $value["payment_type"] ?></td>
				<td><?= $value["transaction_number"] ?></td>
				<td><?= $value["amount_paid"] ?></td>
				<td><?= $value["transaction_date"] ?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	<?php endif; ?>
</table>