<?php /** @var $block \Alfakher\Productpageb2b\Block\Product\ViewDetailRenderer */ ?>
<?php
    $product = $block->getProduct();
    $product_img = $block->getProductImageUrl();
    $attribute = $product->getResource()->getAttribute('brand');
    $brand = $attribute->getFrontend()->getValue($product); 
 ?>

<script type="application/ld+json">
    {
      "@context": "https://schema.org/",
      "@type": "Product",
      "name": "<?= $product->getName()?>",
      "sku": "<?= $product->getSku()?>",
      "image": "<?= $product_img ?>",
      "brand": {
            "@type": "Brand",
            "name": "<?= $brand ?>"
        }
    }
</script>