<?php
/**
 * @var \HookahShisha\Customerb2b\Block\Account\MyProducts $block
 */
?>
<?php 
use Magento\Framework\App\Action\Action;

/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $this->helper(\Magento\Catalog\Helper\Output::class);
$priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
?>
<div class="block-title page-title">
    <h1>My Product Pricing</h1>
</div>

<div class="table-wrapper myproduct-pricing">
    <table class="data table table-myproduct-pricing" id="myproduct-pricing-table">
        <caption class="table-caption"><?= $block->escapeHtml(__('Product Pricing')) ?></caption>
        <thead>
            <tr>
                <th class="col name"><?= $block->escapeHtml(__('Item')) ?></th>
                <th class="col sku"><?= $block->escapeHtml(__('Actual Price')) ?></th>
                <th class="col price"><?= $block->escapeHtml(__('Special Price')) ?></th>
                <th class="col qty"><?= $block->escapeHtml(__('Qty')) ?></th>
                <th class="col action"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
        </thead>
        <?php 
            $sharedCatalog = $block->getSharedCatalogCollection();
        ?>
        <?php if(count($sharedCatalog)): ?>
            <?php foreach ($sharedCatalog as $_product) : ?>
                <tbody>
                    <tr id="order-item-row-<?= (int) $_product->getId() ?>">
                        <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
                            <?php
                            $productImage = $block->getImage($_product, 'category_page_list');
                            $pos = $block->getPositioned();
                            if ($pos != null) {
                                $position = 'left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;';
                            }
                            ?>
                            <?php // Product Image ?>
                            <div class="product_box_info">
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                               class="product photo product-item-photo"
                               tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <div class="merge_box">
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                                </a>
                            </strong>

                            <strong class="product sku product-item-sku"><?= $block->escapeHtml(__('SKU:')) ?> <?= /* @noEscape */ $_product->getSku() ?></strong>
                            </div>
                            </div>
                        </td>

                        <?php 
                            $regularPrice = $_product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue();
                            $specialprice = $_product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
                        ?>
                        <td class="col actual-price" data-th="<?= $block->escapeHtml(__('Actual Price')) ?>">
                            <span class="old-price">
                                <span class="price-container price-final_price tax weee">
                                    <span id="old-price-<?= /* @noEscape */ $_product->getId() ?>" data-price-amount="<?= /* @noEscape */ $regularPrice ?>" data-price-type="oldPrice" class="price-wrapper ">
                                        <span class="price"><?= /* @noEscape */ $priceHelper->currency($regularPrice,true, false); ?></span>
                                    </span>
                                </span>
                            </span>
                        </td>

                        <td class="col special-price" data-th="<?= $block->escapeHtml(__('Special Price')) ?>">
                            <span class="special-price">
                                <span class="price-container price-final_price tax weee">
                                    <span id="product-price-<?= /* @noEscape */ $_product->getId() ?>" data-price-amount="<?= /* @noEscape */ $regularPrice ?>" data-price-type="finalPrice" class="price-wrapper ">
                                        <span class="price"><?= /* @noEscape */ $priceHelper->currency($specialprice,true, false); ?></span>
                                    </span>
                                </span>
                            </span>
                        </td>

                        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
                            <input type="number" name="qty-clone" id="qty-clone" min="0" value="1" title="Qty" class="input-text qty" data-id = "<?= $escaper->escapeHtml($_product->getId()) ?>">
                        </td>

                        <td class="col action" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
                            <div class="actions-primary">
                                <?php if ($_product->isSaleable()):?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form"
                                          data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                          action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                          method="post">
                                        <input type="hidden"
                                               name="product"
                                               value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                        <input type="hidden"
                                               name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                               value="<?=
                                               /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                ?>">
                                        <input type="hidden" name="qty" id="qty" min="0" value="1" title="Qty" class="input-text qty qty-<?= $escaper->escapeHtml($_product->getId()) ?>" >
                                        <?= $block->getBlockHtml('formkey') ?>
                                        <button style="background: transparent;margin-top: 0;letter-spacing: 0;text-transform: none;" type="submit"
                                                title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                class="action tocart primary"
                                                disabled>
                                            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    </form>
                                <?php else:?>
                                    <?php if ($_product->isAvailable()):?>
                                        <div class="stock available">
                                            <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                    <?php else:?>
                                        <div class="stock unavailable">
                                            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </td>
                    </tr>
                </tbody>
                <script type="text/x-magento-init">
                    {
                        "[data-role=tocart-form], .form.map.checkout": {
                            "catalogAddToCart": {
                                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                            }
                        }
                    }
                </script>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="alert"><?= $block->escapeHtml(__('No Data Found')) ?></div>
        <?php endif; ?>
        <tfoot>
            <?php if ($block->getPagerHtml()): ?>
                <div class="order-products-toolbar toolbar bottom">
                    <?= $block->getPagerHtml() ?>
                </div>
        <?php endif ?>
        </tfoot>
    </table>
</div>



<script type="text/javascript">
    require(['jquery'], function ($) 
    {
        $(document).ready(function(){
            $(".input-text.qty").change(function() {
                if(this.value <= 0) {
                    $(this).val(1);
                } else {
                    $('.qty-'+$(this).data("id")).val(this.value);
                }
                console.log('.qty-'+$(this).data("id"));
            }); 
        });
    });
</script>