<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MultiQuickbooksConnect
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited(https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

    $orderList = $block->getOrderList();
    $orderCount = $orderList['items_count'];
    $accountId = $orderList['account_id'];
?>
<fieldset class="fieldset">
    <div class="wk-mu-note wk-mu-box">
        <?= /* @noEscape */ __('Starting Execution'); ?>...
    </div>
    <div class="wk-mu-notice wk-mu-box">
        <?= /* @noEscape */ __("Please don't close or refresh the window while exporting order(s) to Quickbooks."); ?>
    </div>
    <div class="wk-mu-success wk-mu-box">
        <?= /* @noEscape */ __('Total '); ?>
        <?= /* @noEscape */ $orderCount; ?>
        <?= /* @noEscape */ __(' order(s) to export to Quickbooks'); ?>.
    </div>
    <?php if ($orderCount > 0):?>
        <div class="wk-mu-info-bar">
            <?= /* @noEscape */ __('Exporting ');?>
            <span class="wk-current">1</span> of <?= /* @noEscape */ $orderCount;?>
            <?php $loaderSrc = $block->getViewFileUrl('Webkul_MultiQuickbooksConnect::images/loader.gif');?>
            <img id="loader-image" src="<?= /* @noEscape */ $loaderSrc ?>" />
        </div>
        <div class="wk-mu-progress-bar">
            <div class="wk-mu-progress-bar-current"></div>
        </div>
    <?php else:?>
        <div class="wk-mu-note wk-mu-box">
            <?= /* @noEscape */ __('No order to export.');?>
        </div>
        <div class="wk-mu-note wk-mu-box">
            <?= /* @noEscape */ __('Finsihed Execution.');?>
        </div>
    <?php endif; ?>
</fieldset>
<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document).ready(function() {
            var skipCount = 0;
            var importUrl = "<?= /* @noEscape */ $block->getUrl(
                'multiquickbooksconnect/ordermap/createsalesreceipt'
            ); ?>";
            var total = <?= /* @noEscape */ $orderCount; ?>;
            var totalOrder = JSON.parse('<?= /* @noEscape */ $orderList['items_json'] ?>');
            var accountId = <?= /* @noEscape */ $accountId; ?>;
            if(total > 0) {
                importOrderOnQuickbooks(0);
            }
            function importOrderOnQuickbooks(count)
            {
                count = count;
                $.ajax({
                    type: 'get',
                    url:importUrl,
                    async: true,
                    dataType: 'json',
                    data : { 'order_id':totalOrder[count]['entity_id'], 'account_id': accountId},
                    success:function(data) {
                        if(data['error'] == 1) {
                            $(".fieldset").append($('<div />')
                                                    .addClass('message message-error error')
                                                    .text(data['msg'])
                                                );
                            skipCount++;
                        }
                        width = (100/total)*(count+1);
                        $(".wk-mu-progress-bar-current").animate({width: width+"%"},'slow', function() {
                            if(count+1 == total) {
                                finishImporting(count, skipCount);
                                $(".wk-mu-info-bar").text("<?= /* @noEscape */ __('Completed') ?>");
                            } else {
                                count++;
                                $(".wk-current").text(count);
                                importOrderOnQuickbooks(count);
                            }
                        });
                    }
                });
            }
            function finishImporting(count, skipCount)
            {
                $.ajax({
                    type: 'get',
                    url:importUrl,
                    async: true,
                    dataType: 'json',
                    data : {count:count, skip:skipCount, 'order_id':0},
                    success:function(data) {
                        $(".fieldset").append(data['msg']);
                    }
                });
            }
        });
    });
</script>
