<?php
$rejection=$this->getRejectedDoc();
if (!empty($rejection)) { ?>
<h3>Please find your documentation details.</h3>
<table border="1">
	<tr>
    	<th>Document Name</th>
    	<th>Status</th>
    	<th>Comment</th>
	</tr>
<?php foreach ($rejection as $item): ?>

	<tr>
   		<td><?= $item['docname'] ?></td>
    	<td><?= isset($item['docmsg']) ? "Rejected" : "Approved" ?></td>
    	<td><?= isset($item['docmsg']) ? $item['docmsg'] : "-" ?></td>
	</tr>
<?php endforeach; ?>
</table>
<?php } ?>