<?php
$rejection=$block->getDocumentarray();
if (!empty($rejection)) {
    $text = "It has been observed that few documents are expired. ";
    $text .= "Please find a details of expired document as follows:"; ?>
<p>
    <?= $block->escapeHtml(__($text))?>
</p>
<ul>
    <?php foreach ($rejection as $item): ?>
    <li><?= /* @noEscape */ $item['docname'] ?></li>
    <?php endforeach; ?>
</ul> 
<p><?= $block->escapeHtml(__('To re-upload the documents, click here'))?> 
    <a href="<?=  /* @noEscape */ $block->getUrl('mydocument/customer/index'); ?>">
        <?= $block->escapeHtml(__('My Documents'))?> 
    </a>.
</p>
<?php } ?>