<?php
    $customerid = $block->getCustomerId();
    $docdata = $block->getDocumentCollection($customerid);
    $data = $docdata->getData(); ?>

    <div class="document-title"><span class="title">My Documents</span><span class="note">(File type supported are JPG,PNG and PDF,Max file size 20 MB)</span></div>

    <?php if($data!==''){?>
    <?php foreach($data as $val){ ?>
        <div class="uploaded-doc-box">
            <div><a href="<?php echo "/media/".$val['filename'];?>"><?php echo $val['filename'];?></a></div>
            <div><label><?= __('Document Name') ?></label>
                <div class="doc-name"><?= $val['document_name'] ?></div>
            </div>
             <div><label><?= __('Set a Specific Expiry date') ?></label>
                <span>toggle</span>
            </div>
            <div><label><?= __('Set Expiry Date*') ?></label>
                <div class="doc-ex-date"><?= __('Expiry Date:') .$val['expiry_date'] ?></div>
            </div>
        </div>
    <?php } ?>
<?php }
?>
<!-- </div> -->

<!-- <div class="note">
    <span>(File type supported are JPG,PNG and PDF,Max file size 20 MB)</span>
</div> -->
<div class="my_document">
    <form name="myformdynamic" id="myformdynamic" accept-charset="utf-8" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}' method="post">
            <div class="add-more-cont"><a id="add_more"><img src="<?php echo $this->getUrl('static/version1642502197/frontend/Corra/alfakher/en_US/images/'); ?>logo.svg">Add More Document</a></div>
            <div class="upload" for="document uploader">
                <input type="file" id="filename" class="upload-filename" name="filename[]" data-validate="{required:true}"/>
            </div>
            <div class="doc_name" for="document name">
                <div class="label">
                    <label>Document Name</label>
                </div>
                <input type="text" id="name" name="name[]" data-validate="{required:true}" />
            </div>
            <div class="set_expiry" for="document expiry data" >
                <div class="label">
                    <input type="checkbox" id="toggle" name="set_expiry[]" class="cmn-toggle cmn-toggle-round checkbox" >
                    <label>Set a Specific Expiry date
                    </label>
                    </input>
                </div>
                <input type="checkbox" id="toggle" name="set_expiry[]" class="cmn-toggle cmn-toggle-round" >
                <span class="slider round"></span>
                
                <div class="expiry_dates" for="document expiry data" >
                    <input type="text" placeholder="Expiry Date" name="expiry_date[]" id="expiry_date" data-validate="{required:true}" />
                </div>    
            </div>
            <br>


        <button type="submit" id="btnsave" class="action submit primary">
            <span>Submit</span>
        </button>
    </form>
</div>
<div id="popup-modal" >
    <h1>DOCUMENTS ARE UPLOADED SUCCESSFULLY</h1>
    <h5>Once it is approved by Admin, Product price would be visible to you</h5>
</div>


<script>
require(["jquery", "mage/calendar"], function($){
    $(document).ready(function() {
            $("#btnsave").hide();
            $(".set_expiry").hide();
            $(".expiry_dates").hide();
            $('#toggle').on('change', function(){
                   this.value = this.checked ? 1 : 0;
                   if($(this).val() == "1") {
                        /*alert("dfdfds");*/
                        $(".expiry_dates").show();
                        $("#expiry_date").attr("data-validate", "{required:true}");
                        /*$(".expiry_dates").append('<input type="text" id="expiry_date-'+showId+'" name="expiry_date[]">');*/
                   }else{
                        $(".expiry_dates").hide();
                   }


                   $("#expiry_date").datepicker({
                      minDate: 0,
                        // startDate: '-0m',
                      showMonthAfterYear: false,
                      dateFormat:'mm/dd/yy',
                      changeMonth: true,
                      changeYear: true,
                      yearRange: '2020:2030',
                    });

               }).change();;

          $(".doc_name").hide();
          /*$(".expiry").hide();*/
          $('#filename').change( function()
            {
                if ($(this).val()){
                     $(".set_expiry").show();
                    $(".doc_name").show();
                    $("#btnsave").show();
                 } else{
                    $(".set_expiry").hide();
                     $(".doc_name").hide();
                     $("#btnsave").hide();
                 }
            });

          var id = 1;
            $("#add_more").click(function(){
                var showId = ++id;
                if(showId <=10)
                {
                    $(".upload").append('<input type="file" id="filename-'+showId+'" class="upload-filename" name="filename[]">');
                }

            $('#filename-'+showId).change( function()
            {
                if ($(this).val()){
                     $(".doc_name").append('<div class="label"><label>Document Name</label></div><input type="text" id="name-'+showId+'" name="name[]">');
                     $(".set_expiry").append('<div class="label"><label>Set a Specific Expiry date</label></div><input type="checkbox" id="toggle-'+showId+'" name="set_expiry[]" /><span class="slider round"></span>');

                $(document).on('change',"#toggle-"+showId, function() {
                  this.value = this.checked ? 1 : 0;
                   if($(this).val() == "1") {
                        if($("#expiry_date-"+showId).css('display')){ 
                            if($("#expiry_date-"+showId).css('display') == 'none'){
                                $("#expiry_date-"+showId).show();
                            }
                        }else{
                            $(".set_expiry").append('<input type="text" placeholder="Expiry Date" id="expiry_date-'+showId+'" name="expiry_date[]">');    
                        }

                        $("#expiry_date-"+showId).datepicker({
                          showMonthAfterYear: false,
                          dateFormat:'mm/dd/yy',
                          changeMonth: true,
                          changeYear: true,
                          yearRange: '2020:2030',
                        });

                        
                   }else{
                        $("#expiry_date-"+showId).hide();
                   }
                });
                }/*else{
                    $(".expiry").hide();
                     $(".doc_name").hide();
                 }*/
            });

            
            });

            $('#toggle-'+showId).change( function(){
                   this.value = this.checked ? 1 : 0;
                   if($(this).val() == "1") {
                        /*alert("dfdfds");*/
                        /*$(".expiry_dates").show();*/
                        $(".expiry_dates").append('<input type="text" placeholder="Expiry Date" id="expiry_date-'+showId+'" name="expiry_date[]">');
                   }/*else{
                        $(".expiry_dates").hide();
                   }*/

               }).change();;
            
        
        /*$("#myformdynamic").submit(function(){
            
            if ($('#myformdynamic').valid()) {
                $('.page.messages').html('');
                var document_name = $("input[name='name']").val();
                var document_expirydate = $("input[name='expiry_date']").val();
                var formData = new FormData(this);
                var file_obj = document.getElementById("filename");
                formData.append('filename', file_obj.files[0]);

                var url = "<?php echo $block->getBaseUrl().'mydocument/customer/result/' ?>";
                $.ajax({
                    url: url,
                    type: "POST",
                    dataType: "JSON",
                    contentType: false,
                    enctype: 'multipart/form-data',
                    processData: false,
                    //data: {fname:event_fname,lname:event_lname,address:event_address,city:event_city,mobilenumber:event_mobilenumber,filename:event_filename},
                    data: formData,
                    showLoader: true,
                    cache: false,
                    success: function(response){
                        //console.log(response.output);
                        //jQuery('.page.messages').html(response);
                        if(response == "1"){
                            $(".page.messages").html('<div role="alert" class="messages"><div class="message-success success message" data-ui-id="message-success"><div >Insert Record Successfully !</div></div></div>');
                            $('#name').val('');
                            $('#expiry_date').val('');
                            $('#filename').val('');
                        }else{
                            //alert("Not Saved!");
                            $(".page.messages").html('<div role="alert" class="messages"><div class="alert danger alert-danger" data-ui-id="message-danger"><div >Data could not saved ! .</div></div></div>');
                        }
                        $(".page.messages").delay(200).fadeIn().delay(4000).fadeOut();
                    }
                });
                return false;
            }
        });*/
    });    
});
</script>
<script>
    require(["jquery",'Magento_Ui/js/modal/modal'], function($,modal) {
        var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: 'mymodal1',
                    click: function () {
                        this.closeModal();
                        // $("#myformdynamic").reset();
                        $('#myformdynamic').trigger("reset");
                        /*$('#myformdynamic').hide();*/

                    }
                }]
            };
        var popup = modal(options, $('#popup-modal'));

         $("form#myformdynamic").submit(function(e) {
            e.preventDefault();
            var formData = new FormData(this);
            var url = "<?php echo $block->getBaseUrl().'mydocument/customer/result/' ?>";
            $.ajax({
                url: url,
                type: 'POST',
                data: formData,
                /*showLoader: true,*/
                dataType: 'json',
                success: function(data) {
                    console.log(data.html);
                    console.log(data.success);
                    if(data.success==1){
                        console.log("success if conditon");
                        $('#myformdynamic').trigger("reset");
                        $("#popup-modal").modal("openModal");
                    }else{
                        $(".page.messages").html('<div role="alert" class="messages"><div class="alert danger alert-danger" data-ui-id="message-danger"><div >Data could not saved ! .</div></div></div>');
                        $(".page.messages").delay(200).fadeIn().delay(4000).fadeOut();
                    }
                },
                cache: false,
                contentType: false,
                processData: false,
            });
         });
    });

</script>



