<?php
/**
 * Webkul Software.
 *
 * @category Webkul
 * @package Webkul_MultiQuickbooksConnect
 * @author Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */
?>
<script type="text/x-magento-init">
    {
        "*":{
            "Webkul_MultiQuickbooksConnect/js/creditmemomap/map":""
        }
    }
</script>
