<?php
//phpcs:disable 
/** @var $block \Magento\Rma\Block\Order\Button */
?>
<?php $viewModel = $block->getData('view_model');?>
<?php if ($this->helper(Magento\Rma\Helper\Data::class)->canCreateRma($block->getOrder())): ?>
    <a href="<?= $block->escapeUrl($this->helper(Magento\Rma\Helper\Data::class)
        ->getReturnCreateUrl($block->getOrder())) ?>" 
        class="action return"><span><?= $block->escapeHtml(__('Return Particular Items')) ?></span></a>
    <a href="<?= $block->escapeUrl($this->helper(Alfakher\RmaCustomization\Helper\Data::class)
        ->getReturnCreateUrl($block->getOrder())) ?>" 
        class="action return"><span><?= $block->escapeHtml(__('Return All Items')) ?></span></a>
<?php endif;?>
