<?php $helper = $this->helper('HookahShisha\ChangePassword\Helper\Data'); ?>
<div class="reorder-wrapper">
    <?php if($helper->customerLoggedIn()): ?>
        <a class= "header_account_link" href="<?php echo $this->getUrl("sales/order/history");?>"><?php echo __('Reorder')?></a>
    <?php else: ?>
        <a class= "header_account_link" href="<?php echo $this->getUrl("customer/account/login");?>"><?php echo __('Reorder')?></a>
    <?php endif; ?>
</div>
