<?php
// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Customer\Block\Address\Edit $block */
?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<?php $addressHelper = $this->helper(\Magento\Customer\Helper\Address::class); ?>
<?php $directoryHelper = $this->helper(\Magento\Directory\Helper\Data::class); ?>
<?php
/* Start Change the region_id Label if the Country is US for State and Other for the State */
$regionStateLabel = $block->escapeHtml(__('State'));
$regionProvinceLabel = $block->escapeHtml(__('Province'));
$regionLabel = ($block->getCountryId() == 'US') ? $regionStateLabel:$regionProvinceLabel;
/* End Change the region_id Label if the Country is US for State and Other for the State */
?>
<?php
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('address-form')
    ->toHtml();
?>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                <?php if ($block->getPostCodeConfig()): ?>
                    "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
    <?php endif; ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block
        ->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $directoryHelper->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $directoryHelper->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<script>
    function onCountryChange() {
        require(['jquery'], function($){
            var countryval = $('#country option:selected').val();
            if (countryval=='US') {
                $('#region_id_label').children('span').html("<?= $block->escapeHtmlAttr($regionStateLabel) ?>");
                $('#region_id').attr('placeholder',"<?= $block->escapeHtmlAttr($regionStateLabel) ?>");
            } else {
                $('#region_id_label').children('span').html("<?= $block->escapeHtmlAttr($regionProvinceLabel) ?>");
                $('#region').attr('placeholder',"<?= $block->escapeHtmlAttr($regionProvinceLabel) ?>");
            }
        });
    }
    require(['jquery', 'jquery/ui','mage/mage'], function($){
        $(document).ready(function(){
            if($('div').hasClass('message info') == true){
                $("#form-validate #country").attr("disabled","true");
            }
        });
        $("#country").change(function () {
            onCountryChange();
        });
    });
</script>
<?php if ($block->isDefaultBilling()): ?>
    <script>
        require(['jquery','jquery/ui','mage/mage'], function($){
            //right before the form submits, we re-enable the fields, to make them submit.
            $("#form-validate").submit(function( event ) {
                if($('#form-validate').valid()){
                    $("body").trigger('processStart');
                    $("#country").prop("disabled", false);
                }
            });
        });
    </script>
<?php endif; ?>
