<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class); ?>
<?php /* @var $block \Magento\ProductAlert\Block\Product\View */?>
<?php
$productId = $block->getCurrentProductId();
$_product = $block->getProduct();
$notifyText = __('NOTIFY WHEN BACK IN STOCK');
?>
<div class="product alert <?= $block->getHtmlClass() ?>">
<?php if ($_helperB2b->isCustomerLoggedIn()): ?>
<div class="actions">
    <div class = "Product_grouped_totals">
        <span>Total</span>
        <span id = "Product_price_grouped">$0.00</span>
    </div>
    <div class = "product_notify_me">
        <a href="<?= $block->escapeUrl($block->getSignupUrl()) ?>"
        title="<?= $block->escapeHtml($notifyText) ?>" class="action alert">
        <span><?= $block->escapeHtml($notifyText) ?></span>
        </a>
    </div>
</div>
<?php else: ?>
    <div class="actions">
    <?php if (isset($_product->isSaleable)):?>
    <div class = "Product_grouped_totals">
        <span>Total</span>
        <span id = "Product_price_grouped">$0.00</span>
    </div>
    <?php endif; ?>
    <div class = "product_notify_me">
    <a
        title="<?= $block->escapeHtml($notifyText) ?>" class="action alert notifyme_button">
        <span><?= $block->escapeHtml($notifyText) ?></span>
</a>
    </div>
</div>
<?php endif; ?>
</div>
<div id="modal" style = "display:none;">
    <div class="modal-body-content">
    <form name="login_form"
    action="<?= $block->getUrl("outofstock/productalert/save/", ['product_id' => $productId])?>"
    method="post" role="form">
            <div class="modal-body">
                <div class="form-group">
                      <input type="text" class="form-control" name="name" id="Full Name"
                       placeholder="Full Name"  data-validate='{"required":true}'>
                </div>

                <div class="form-group">
                      <input type="email" class="form-control" name="email" id="email"
                       placeholder="Email Id" data-validate='{"required":true, "validate-email":true}'>
                </div>
            </div>
            <div class="modal-notify-buttons">
                <button class="action-secondary-cancel" type = "button">Cancel</button>
                <button class="action-secondary" type = "submit">NOTIFY ME</button>
        </div>
    </form>
    </div>
</div>


<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: 'Remind me when the product is back In Stock!',
            modalClass: 'small-modal',
        };

        var popup = modal(options, $('#modal'));
        $(".notifyme_button").click(function() {
            $('#modal').modal('openModal');
        });
        $(".action-secondary-cancel").click(function() {
            $('#modal').modal('closeModal');
        });
    });
</script>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($) {
        $(document).ready(function() {
            var dataForm = $('#login_form');
            dataForm.mage('validation', {});

            dataForm.submit(function(event) {
                var isValid = dataForm.valid();
                if (!isValid) {
                    event.preventDefault(); // Prevent form submission if validation fails
                }
            });
        });
    });
</script>

