<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class); ?>
<?php /* @var $block \Magento\ProductAlert\Block\Product\View */?>
<?php
$notifyText = __('NOTIFY WHEN BACK IN STOCK');
?>
<div class="product alert <?= $block->getHtmlClass() ?>">
<?php if ($_helperB2b->isCustomerLoggedIn()): ?>
<div class="actions">
    <div class = "Product_grouped_totals">
        <span>Total</span>
        <span id = "Product_price_grouped">$0.00</span>
    </div>
    <div class = "product_notify_me">
        <a href="<?= $block->escapeUrl($block->getSignupUrl()) ?>"
        title="<?= $block->escapeHtml($notifyText) ?>" class="action alert">
        <span><?= $block->escapeHtml($notifyText) ?></span>
        </a>
    </div>
</div>
<?php else: ?>
    <div class="actions">
    <div class = "Product_grouped_totals">
        <span>Total</span>
        <span id = "Product_price_grouped">$0.00</span>
    </div>
    <div class = "product_notify_me">
    <a
        title="<?= $block->escapeHtml($notifyText) ?>" class="action alert notifyme_button">
        <span><?= $block->escapeHtml($notifyText) ?></span>
</a>
    </div>
</div>
<?php endif; ?>
</div>
<div id="modal">
    <div class="modal-body-content">
    <form name="login_form" action="<?= $block->getUrl('outofstock/productalert/save')?>" method="post" role="form">
            <div class="modal-body">
                <div class="form-group">
                      <input type="text" class="form-control" id="Full Name" placeholder="Full Name">
                </div>

                <div class="form-group">
                      <input type="email" class="form-control" id="email" placeholder="Email Id">
                </div>
            </div>
            <div class="modal-notify-buttons">
                <button class="action-secondary-cancel" type = "button">Cancel</button>
                <button class="action-secondary" type = "submit">NOTIFY ME</button>
        </div>
    </form>
    </div>
</div>


<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: 'Remind me when the product is back In Stock!',
            modalClass: 'small-modal',
        };

        var popup = modal(options, $('#modal'));
        $(".notifyme_button").click(function() {
            $('#modal').modal('openModal');
        });
        $(".action-secondary-cancel").click(function() {
            $('#modal').modal('closeModal');
        });
    });
</script>

