<?php
/**
 * Webkul MultiQuickbooksConnect
 * @category  Webkul
 * @package   Webkul_MultiQuickbooksConnect
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited(https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<style type="text/css">
    .pp-buttons-container .intuitPlatformConnectButton {
        display: block;
        margin-top: 20px;
    }
    .mark::before {
        font-family: 'Admin Icons';
        font-size: 1.5rem;
        position: relative;
        top: -30px;
        left: 110px;
    }
    .mark.expired:before {
        color: #e22626;
        content: '\e632  Expired';
    }
    .mark.notexpired:before {
        color: #79a22e;
        content: '\e62d Authorized';
    }
    .pp-buttons-container.notexpired {
        pointer-events: none;
    }
    body.quickbooksconnect-oauth-oauthbutton {
        background-color: #FFF;
        min-height: auto;
        min-width: auto;
    }
</style>

