<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MultiQuickbooksConnect
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited(https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<script type="text/javascript">
(function ($) {
    $(function(){
        $("#quickbooks_map_order_massaction-select, #quickbooks_export_order_massaction-select")
            .removeClass("required-entry local-validation");
        $("#quickbooks_map_creditmemo_massaction-select, #quickbooks_export_creditmemo_massaction-select")
            .removeClass("required-entry local-validation");
    })
})(jQuery);
</script>
