
<?php  $viewModel = $block->getViewModel(); ?>

<?php /* @var $block \Magento\ProductAlert\Block\Product\View */?>
<div class="product alert <?= $block->getHtmlClass() ?>">

<?php if ($viewModel->canShowPopup()): ?>
    <?php if ($viewModel->isGuestAlertEnabled()): ?>
        <a href="#"
           title="<?= $block->escapeHtml(__($block->getSignupLabel())) ?>" class="action alert" id="alert">
            <?= $block->escapeHtml(__($block->getSignupLabel())) ?>
        </a>
    <?php endif; ?>
<?php else: ?>
    <a href="<?= $block->escapeUrl($block->getSignupUrl()) ?>"
       title="<?= $block->escapeHtml(__($block->getSignupLabel())) ?>" class="action alert">
        <?= $block->escapeHtml(__($block->getSignupLabel())) ?>
    </a>
<?php endif; ?>
</div>

<div id="popup-modal" style="display:none;">
    <!-- Popup content for non-logged-in users -->
    <form id="stock-notification-form" method="post"
          action="<?php /* @noEscape */ $block->getUrl('outofstock/productalert/save') ?>">
        <input type="hidden" name="product_id" value="<?= /* @noEscape */ $viewModel->getProductId()?>">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email">
        <button type="submit">Notify Me</button>
    </form>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            let options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'popup modal title',
            };

            let popup = modal(options, $('#popup-modal'));
            $("#alert").on('click',function(){
                $("#popup-modal").modal("openModal");
            });


        }
    );
</script>



