<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?> 
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label">
            <?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?>
        </div>
        <div class="field first_name">
            <label class="label" for="first_name"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
            <div class="control">
                <input name="first_name"
                       id="first_name"
                       title="<?= $block->escapeHtmlAttr(__('First Name')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getFirstName()) ?>"
                       class="input-text"
                       type="text"/>
            </div>
        </div>
        <div class="field last_name">
            <label class="label" for="last_name">
                <span><?= $block->escapeHtml(__('Last Name')) ?></span>
            </label>
            <div class="control">
                <input name="last_name"
                       id="last_name"
                       title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getLastName()) ?>"
                       class="input-text"
                       type="text" />
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span>
            <?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone"
                       id="telephone"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                       class="input-text"
                       type="tel" />
            </div>
        </div>
        <div class="field tax_id">
            <label class="label" for="tax_id"><span>
            <?= $block->escapeHtml(__('Sales Tax ID or EIN Number')) ?></span></label>
            <div class="control">
                <input name="tax_id"
                       id="tax_id"
                       title="<?= $block->escapeHtmlAttr(__('Sales Tax ID or EIN Number')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getTaxId()) ?>"
                       class="input-text"
                       type="text" />
            </div>
        </div>
        <div class="field tobacco_permit_number">
            <label class="label" for="tobacco_permit_number"><span>
            <?= $block->escapeHtml(__('Tobacco Permit Number')) ?></span></label>
            <div class="control">
                <input name="tobacco_permit_number"
                       id="tobacco_permit_number"
                       title="<?= $block->escapeHtmlAttr(__('Tobacco Permit Number')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getTobaccoPermitNumber()) ?>"
                       class="input-text"
                       type="text" />
            </div>
        </div>
        <div class="field issue_type input-box required">
                <label class="label" for="issue_type"><span>
                <?= $block->escapeHtml(__('Issue Type')) ?></span></label>
            <div class="control">
                <select name="issue_type" id="issue_type" data-validate="{required:true}">
                    <option value="">Please Select</option>
                    <option name="Order Status" value="Order Status">Order Status</option>
                    <option name="Order Change" value="Order Change">Order Change</option>
                    <option name="Order Cancellation" value="Order Cancellation">Order Cancellation</option>
                    <option name="Out of Stock" value="Out of Stock">Out of Stock</option>
                    <option name="Lost Order" value="Lost Order">Lost Order</option>
                    <option name="Damaged Order" value="Damaged Order">Damaged Order</option>
                    <option name="Wrong Item" value="Wrong Item">Wrong Item</option>
                    <option name="Missing Item" value="Missing Item">Missing Item</option>
                    <option name="Product Issue" value="Product Issue">Product Issue</option>
                    <option name="Return" value="Return">Return</option>
                </select>
            </div>
        </div>
        <div class="field subject required">
            <label class="label" for="subject"><span>
            <?= $block->escapeHtml(__('Subject')) ?></span></label>
            <div class="control">
                <input name="subject"
                       id="subject"
                       title="<?= $block->escapeHtmlAttr(__('Subject')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getSubject()) ?>"
                       class="input-text"
                       type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment">
                <span><?= $block->escapeHtml(__('Comments/Questions')) ?></span>
            </label>
            <div class="control">
                <textarea name="comment"
                          id="comment"
                          title="<?= $block->escapeHtmlAttr(__('Comments/Questions')) ?>"
                          class="input-text"
                          cols="5"
                          rows="3"
                          data-validate="{required:true}"
                ><?= $block->escapeHtml($viewModel->getUserComment()) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>
