<?php
/**
 * @var \Magento\Sales\Block\Adminhtml\Order\View $block
 */
$payment = $block->getOrder()->getPayment();
$method = $payment->getMethodInstance()->getCode();
?>
<?php if ($method == 'offline_paypal'):?>
<div class="admin__page-section-item-content">
    <strong><?= $block->escapeHtml(__('PayPal Email:')) ?></strong>
    <span class="info"><?= $block->escapeHtmlAttr($payment->getData('paypal_email')); ?></span>                        
</div>
<?php endif; ?>
<?php if ($method == 'ach_us_payment'):?>
<div class="admin__page-section-item-content">
    <span class="info">
        <strong><?= $block->escapeHtml(__('Account Number :')) ?></strong>                 
    </span>
    <span class="info"><?= $block->escapeHtmlAttr($payment->getData('account_number')); ?></span> 
</div>
<div class="admin__page-section-item-content">
    <span class="info">
        <strong><?= $block->escapeHtml(__('Name of Bank :')) ?></strong>                 
    </span>    
    <span class="info"><?= $block->escapeHtmlAttr($payment->getData('bank_name')); ?></span>
</div>
<div class="admin__page-section-item-content">    
    <span class="info">
        <strong><?= $block->escapeHtml(__('Routing Number :')) ?></strong>                 
    </span>
    <span class="info"><?= $block->escapeHtmlAttr($payment->getData('routing_number')); ?></span>
</div>
<div class="admin__page-section-item-content">    
    <span class="info">
        <strong><?= $block->escapeHtml(__('Address :')) ?></strong>                 
    </span>
    <span class="info"><?= $block->escapeHtmlAttr($payment->getData('address')); ?></span>                       
</div>
<?php endif; ?>