<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MultiQuickbooksConnect
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited(https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>

<?php
$rateList = $block->getTaxRateList();
$notification = __('You need to create following tax rates on quickbooks end for sync tax detail with orders.');
?>
<div><div class="messages"><div class="message message-notice notice">
    <div data-ui-id="messages-message-notice"><?= /* @noEscape */ $notification ?></div>
</div></div></div>
<fieldset class="admin__fieldset">
    <div class="admin__field admin__field-wide _no-header">
        <div class="admin__field-control">
            <div class="admin__control-table-wrapper">
                <table class="admin__dynamic-rows admin__control-table">
                    <thead>
                        <tr>
                            <th></th>
                            <th class="_no-header"><span><?= /* @noEscape */ __('Tax Code')?></span></th>
                            <th class="_no-header"><span><?= /* @noEscape */ __('Tax Rate')?></span></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($rateList as $rate => $code) { ?>
                            <tr class="data-row">
                                <td class="col-draggabl"><div class="draggable-handle"></div></td>
                                <td class="_no-header">
                                    <div class="admin__field _no-header">
                                        <div class="admin__field-control">
                                            <div class="control-table-text">
                                                <span data-index="name"><?= /* @noEscape */ $code?></span>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="_no-header">
                                    <div class="admin__field _no-header" data-index="sku">
                                        <div class="admin__field-control">
                                            <div class="control-table-text">
                                                <span><?= /* @noEscape */ (float)$rate?> %</span>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</fieldset>
