<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<div class="col-2-sub <?php if ($block->isEditMode() && $block->isBillingEditable()):
    echo 'col-1-sub';
endif; ?>">
        <strong class="box-title">
            <span><?php echo __('Billing Address') ?></span>
        </strong>
        <div class="box-content">
            <?php if ($block->isEditMode() && $block->isBillingEditable()): ?>
                <select id="md_billing_address" name="md_billing_address" class="validate-select required-entry" aria-required="true">
                    <?php foreach ($block->getAllAddress('billing') as $id => $address): ?>
                        <option value="<?php echo $id?>" <?php echo ($address['is_current'])?"selected='selected'":""; ?>>
                            <?php echo $address['data'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            <?php else: ?>
                <address><?php  echo $block->getCustomerAddress('billing'); ?></address>
            <?php endif; ?>
        </div>
</div>
<?php if ($block->canShowShippingAddress()): ?>
<div class="col-2-sub <?php if ($block->isEditMode() && $block->isShippingEditable()):
    echo 'col-1-sub';
endif; ?>">
    <strong class="box-title">
        <span><?php echo __('Shipping Address') ?></span>
    </strong>
    <div class="box-content">
        <?php if ($block->isEditMode() && $block->isShippingEditable()): ?>
            <select id="md_shipping_address" name="md_shipping_address"  class="validate-select required-entry" aria-required="true">
                <?php foreach ($block->getAllAddress('shipping') as $id => $address): ?>
                    <option value="<?php echo $id?>" <?php echo ($address['is_current'])?"selected='selected'":""; ?>>
                        <?php echo $address['data'] ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php else: ?>
            <address><?php echo $block->getCustomerAddress('shipping'); ?></address>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>