<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<table class="info-table">
    <tbody>
    <tr>
        <th><span class="nobr"><?php echo __('Profile Number:'); ?></span></th>
        <td><?php echo '#' . $block->getSubscription()->getProfileId(); ?></td>
    </tr>
    <tr>
        <th><span class="nobr"><?php echo __('Profile Status:'); ?></span></th>
        <td><?php echo $block->getSubscriptionStatus(); ?></td>
    </tr>
    <tr>
        <th><span class="nobr"><?php echo __('Product Name:'); ?></span></th>
        <td>
            <?php if ($block->getProductUrl() == '#'): ?>
                <?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getSubscription()->getProductName()); ?>
            <?php else: ?>
            <a href="<?php echo $block->getProductUrl(); ?>" target="_blank">
                    <?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getSubscription()->getProductName()); ?>
                </a>
            <?php endif; ?>

            <?php if ($productOptions = $block->getProductOption()) { ?>
                <dl class="item-options">
                    <?php foreach ($productOptions as $optionKey => $option) { ?>
                        <dt><?= $option['label'] ?> :</dt>
                        <dd><?= $option['value'] ?></dd>
                    <?php } ?>
                </dl>
            <?php } ?>
        </td>
    </tr>
    <tr>
        <th><span class="nobr"><?php echo __('SKU:'); ?></span></th>
        <td><?php echo $block->getSubscription()->getProductSku(); ?></td>
    </tr>
    <tr>
        <th><span class="nobr"><?php echo __('Quantity:'); ?></span></th>
        <td>
        <?php if ($block->isEditMode()): ?>
            <input type="text"
                   name="qty"
                   value="<?php echo $block->getQtyOrdered() ?>"
                   class="input-text required-entry validate-greater-than-zero validate-digits"
                   aria-required="true"
            />
        <?php else: ?>
            <?php echo $block->getQtyOrdered() ?>
        <?php endif; ?>
        </td>
    </tr>
    </tbody>
</table>

