<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

?>
<?php
// check size of category start[BS]14/02/2022
$size=[];
$size=$block->getCollection();
if (!empty($size)) {
    if ($block->getCollection()->getSize()):?>
        <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
        $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
        ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <?php if ($block->isExpanded()):?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

        <?= $block->getPagerHtml() ?>

        <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
        
        <?php if ($block->isExpanded()):?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
             <div class="cate-filter"><a href="javascript:void(0)" class="filter_button" id="is_filter"><span id="filter_text">Hide Filter</span></a></div>
        <?php endif; ?>
    </div>
<?php endif;
}
// check size of category end[BS]14/02/2022
?>
<?php /* show/hide filter start vy */ ?>
<script>
    require(['jquery'], function($) {
        if($("div").hasClass("filter-collapse")){
            $("#filter_text").html('Show Filter');
        }else{
             $("#filter_text").html('Hide Filter');
        }
        $(document).on("click", '.cate-filter', function(event) { 
            if ($(".sidebar.sidebar-main").css("display") == 'block') {       
                $("#filter_text").html('Show Filter');
                $(".sidebar.sidebar-main").css("display", "none");
                $(".column.main").addClass("filter-collapse");
            } else {
                $("#filter_text").html('Hide Filter');
                $(".sidebar.sidebar-main").css("display", "block");
                $(".column.main").removeClass("filter-collapse");
            }
        });
    });
</script>
<?php /* End */ ?>