<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

?>
<?php
// check size of category start[BS]14/02/2022
$size=[];
$size=$block->getCollection();
if(!empty($size)){
 if ($block->getCollection()->getSize()):?>
    <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
        $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <?php if ($block->isExpanded()):?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

        <?= $block->getPagerHtml() ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
        
        <?php if ($block->isExpanded()):?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
            <div class="cate-filter"><a href="javascript:void(0)" class="filter_button" id="is_filter">Filter</a></div>
        <?php endif; ?>
    </div>
<?php endif;
 }
// check size of category end[BS]14/02/2022
?>
<script>
    require(['jquery'], function($) {
        $("#is_filter").click(function(){
              if ($(".sidebar.sidebar-main").css("display") == 'block') {
                    $(".sidebar.sidebar-main").css("display", "none");
                    $(".column.main").addClass("filter-collapse");                    
              } else {
                    $(".sidebar.sidebar-main").css("display", "block");
                    $(".column.main").removeClass("filter-collapse");
              }
        });
    });
</script>