<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $_helperB2b = $block->helper(Alfakher\Productpageb2b\Helper\Data::class); ?>
<?php $is_document_upload = $_helperB2b->getDocuments();?>

<div class="table-wrapper grouped">
    <table class="table data grouped"
           id="super-product-table"
           data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'>
        <caption class="table-caption"><?= $block->escapeHtml(__('Grouped product items')) ?></caption>
        <?php if ($_hasAssociatedProducts): ?>
        <tbody>
            <?php foreach ($_associatedProducts as $_item): ?>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                    <strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
                </td>
                <!-- show price start -->
                 <?php if ($_helperB2b->getDocMessageData() == 2 && $is_document_upload == 1): ?>
                <td>
                        <?php if ($block->getCanShowProductPrice($_product)): ?>
                            <?php if ($block->getCanShowProductPrice($_item)): ?>
                                <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                    <?php endif; ?>

                        <?php /* bv_op; date : 10-2-22; Start */ ?>
                    <div class="bv-special-price-<?= $block->escapeHtmlAttr($_item->getId()) ?>"></div>
                        <?php /* bv_op; date : 10-2-22; End */ ?>

                </td>
                        <?php if ($_helperB2b->isCustomerLoggedIn()): ?>
                            <?php if ($_product->isSaleable()): ?>
                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                                <?php if ($_item->isSaleable()): ?>
                    <div class="control qty">
                        <input type="number"
                               name="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                               data-selector="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                               value="<?= $block->escapeHtmlAttr($_item->getQty() * 1) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"
                               data-product-id="<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                               onclick="this.select();"/>
                    </div>
                <?php else: ?>
                    <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                    </div>
                <?php endif; ?>
                <?php endif; ?>
                </td>
                <?php endif; ?>
                <?php endif; ?>
            </tr>
                <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))): ?>
                <tr class="row-tier-price" style="display: none;">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
        <?php else: ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else: ?>3<?php endif; ?>">
                    <?= $block->escapeHtml(__('No options of this product are available.')) ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>


<?php /* bv_op; date : 10-2-22; Start */ ?>
<script>
    require(['jquery'], function ($) {

        $(".col.qty .control.qty .input-text.qty").on("change paste keyup", function (e) {

            if (typeof $(this).val() !== 'undefined' && $(this).val() != '' && $(this).val() > 0) {
                var requestQty = parseInt($(this).val());
                var productId = $(this).data('product-id');
                var exist = $("[name='"+productId+"-qty[]']").length;
                if(exist && typeof exist !== 'undefined'){
                    var bvSpecialPrice = 0;
                    $.each($("[name='"+productId+"-qty[]']"), function (index, value) {
                        var bvSpecialPriceQty = parseInt($(value).val());
                        if (requestQty >= bvSpecialPriceQty) {
                            bvSpecialPrice = $("[name='"+productId+"-qty-"+$(value).val()+"']").val();
                        }
                    });

                    if (bvSpecialPrice != 0) {
                        $(".bv-special-price-"+productId).html("<span><strong>$"+parseFloat(bvSpecialPrice).toFixed(2)+"</strong></span>");
                        $(this).parents('td').prev('td').find("span.price").addClass('old-price');
                    }else{
                        $(".bv-special-price-"+productId).html("");
                        $(this).parents('td').prev('td').find("span.price").removeClass('old-price');
                    }
                }

            }else{
                var productId = $(this).data('product-id');
                $(".bv-special-price-"+productId).html("");
                $(this).parents('td').prev('td').find("span.price").removeClass('old-price');
            }

        });

    });
</script>
<?php /* bv_op; date : 10-2-22; End */ ?>