<?php
/**
 * My account form template
 *
 * @var $block \HookahShisha\Customerb2b\Block\Myaccount $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php $message = $block->getMessageData(); ?>
<?php foreach ($message['message'] as $key => $value): ?>
    <div class="<?= $block->escapeHtml(__($value[0])) ?>"><?= $block->escapeHtml(__($value[1])) ?></div>
<?php endforeach; ?>