<?php


/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\AbstractOrder
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Shipping\Helper\Data $shippingHelper */
$shippingHelper = $block->getData('shippingHelper');
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()):
    return '';
endif; ?>

<?php
/* render tracking url  */
function getTrackingUrl($carrier, $trackNumber):string {
    switch ($carrier) {
        case 'usps':
            $trackingDetail = "https://tools.usps.com/go/TrackConfirmAction?qtc_tLabels1=".$trackNumber;
            break;
        case 'ups':
            $trackingDetail = "https://www.ups.com/track?loc=null&tracknum=".$trackNumber."&requester=WT/trackdetails";
            break;
        case 'dhl':
            $trackingDetail = "https://www.dhl.com/us-en/home/tracking/tracking-express.html?submit=1&tracking-id=".$trackNumber;
            break;
        default:
            return $trackNumber;
    }
    return <<<HTML
    <a href="{$trackingDetail}" target="_blank">{$trackNumber}</a>
HTML;
}
?>
<div class="admin__page-section-item order-shipping-method">
    <div>
        <?php  if ($order->getTracksCollection()->count()): ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Tracking information:')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <?php foreach ($order->getTracksCollection() as $trackingInfo): ?>
                        <tr>
                            <th><?= $trackingInfo->getTitle() ?></th>
                            <td><?= getTrackingUrl($trackingInfo->getCarrierCode(),$trackingInfo->getTrackNumber()) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php endif; ?>
        <br/>
    </div>
    <div class="admin__page-section-item-title">
        <span class="title"><?= $block->escapeHtml(__('Shipping &amp; Handling Information')) ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php if ($order->getShippingDescription()): ?>
            <strong><?= $block->escapeHtml($order->getShippingDescription()) ?></strong>

            <?php if ($taxHelper->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?= /** @noEscape */ $_excl ?>
            <?php if ($taxHelper->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?= $block->escapeHtml(__('Incl. Tax')) ?> <?= /** @noEscape */ $_incl ?>)
            <?php endif; ?>


            <?php if($order->getShippingMethod() == "customercourieraccount_customercourieraccount"): ?>
            	<p><strong>Courier Name: </strong><?= $order->getCustomerCourierName() ?></p>
                <p><strong>Account Number: </strong><?= $order->getCustomerCourierAccount() ?></p>
            <?php endif; ?>


        <?php else: ?>
            <?= $block->escapeHtml(__('No shipping information available')) ?>
        <?php endif; ?>
    </div>
</div>
