<div class="documents_required_message">
<?php
    $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class);
    $documents_required_msg = $_helperB2b->getConfigValue('hookahshisha/productpage/productpageb2b_documents_verification_required');?>
     <?=$documents_required_msg;?>

</div>
<div id="non_usa_customer_tab" class="basic_details_tab" style="display: none;">
    <?= $block->getChildHtml('mydoc_non_usa'); ?>
</div>
<div id="usa_customer_tab" class="document_details_tab" style="display: none;">
    <?= $block->getChildHtml('mydoc_usa'); ?>
</div>