<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
    $attributeCodes = [
    'vase_style_title',
    'vase_style',
    'screw_on_vase_capability_title',
    'screw_on_vase_capability',
    'multi_hose_capability_title',
    'multi_hose_capability',
    'included_accessories_title',
    'included_accessories',
    'colors_title',
    'colors',
    'hookah_brand_title',
    'hookah_brand',
    'hookah_size_title',
    'hookah_size',
    'hookah_country_of_manufacture_title',
    'hookah_country_of_manufacture'];
    $shouldDisplaySpecs = false;
    foreach ($attributeCodes as $attributeCode) {
        if ($_product->getData($attributeCode) !== null) {
            $shouldDisplaySpecs = true;
            break;
        }
    }
?>
  <?php $attributeVaseTitle = $_product->getData('vase_style_title') ?>
  <?php $attributeVaseValue = $_product->getData('vase_style') ?>
  <?php $attributeScrewTitle = $_product->getData('screw_on_vase_capability_title') ?>
  <?php $attributeScrewValue = $_product->getData('screw_on_vase_capability') ?>
  <?php $attributeMultiTitle = $_product->getData('multi_hose_capability_title') ?>
  <?php $attributeMultiValue = $_product->getData('multi_hose_capability') ?>
  <?php $attributeAccessoriesTitle = $_product->getData('included_accessories_title') ?>
  <?php $attributeAccessoriesValue = $_product->getData('included_accessories') ?>
  <?php $attributeColorTitle = $_product->getData('colors_title') ?>
  <?php $attributeColorValue = $_product->getData('colors') ?>
  <?php $attributeBrandTitle = $_product->getData('hookah_brand_title') ?>
  <?php $attributeBrandValue = $_product->getData('hookah_brand') ?>
  <?php $attributeSizeTitle = $_product->getData('hookah_size_title') ?>
  <?php $attributeSizeValue = $_product->getData('hookah_size') ?>
  <?php $attributeCountryTitle = $_product->getData('hookah_country_of_manufacture_title') ?>
  <?php $attributeCountryValue = $_product->getData('hookah_country_of_manufacture') ?>
<?php if ($shouldDisplaySpecs): ?>
<div class ="main_wrapper">
<div class="product_attributes">
<div class = "Product_attributes_head">
<span>
Al Fakher Tobacco Specs
</span>
</div>
<table id="t">
<caption></caption>
  <tbody>
    <th></th>
    <th></th>
    <tr>
    <?php if (!empty($attributeVaseValue) && !empty($attributeVaseTitle)) :?>
       
      <td class="td_first">
        <?= /* @noEscape */  $attributeVaseTitle; ?>
      </td>
      <td>
        <?= /* @noEscape */  $attributeVaseValue; ?>
      </td>
    <?php endif; ?>
    </tr>
    <tr>
    <?php if (!empty($attributeScrewValue) && !empty($attributeScrewTitle)) :?>
         
      <td class="td_first">
        <?= /* @noEscape */  $attributeScrewTitle; ?>
      </td>
      <td>
        <?= /* @noEscape */  $attributeScrewValue; ?>
      </td>
    <?php endif; ?>
    </tr>
    <tr>
    <?php
        if (!empty($attributeMultiValue) && !empty($attributeMultiTitle)) :?>
        
      <td class="td_first">
        <?= /* @noEscape */  $attributeMultiTitle; ?>
      </td>
      <td>
        <?= /* @noEscape */  $attributeMultiValue; ?>
      </td>
    <?php endif; ?>
    </tr>
    <tr>
    <?php if (!empty($attributeAccessoriesValue) && !empty($attributeAccessoriesTitle)) :?>
         
      <td class="td_first">
        <?= /* @noEscape */  $attributeAccessoriesTitle; ?>
      </td>
      <td>
        <?= /* @noEscape */  $attributeAccessoriesValue; ?>
      </td>
    <?php endif; ?>
    </tr>
    <tr>
    <?php if (!empty($attributeColorValue) && !empty($attributeColorTitle)) :?>
     
      <td class="td_first">
        <?= /* @noEscape */  $attributeColorTitle; ?>
      </td>
      <td>
        <?= /* @noEscape */  $attributeColorValue; ?>
      </td>
    <?php endif; ?>
    </tr>
    <tr>
    <?php if (!empty($attributeBrandValue) && !empty($attributeBrandTitle)) :?>
          
      <td class="td_first">
        <?= /* @noEscape */  $attributeBrandTitle; ?>
      </td>
      <td>
        <?= /* @noEscape */  $attributeBrandValue; ?>
      </td>
    <?php endif; ?>
    </tr>
    <tr>
    <?php if (!empty($attributeSizeValue) && !empty($attributeSizeTitle)) :?>
         
      <td class="td_first">
        <?= /* @noEscape */  $attributeSizeTitle; ?>
      </td>
      <td>
        <?= /* @noEscape */  $attributeSizeValue; ?>
      </td>
    <?php endif; ?>
    </tr>
    <tr>
    <?php if (!empty($attributeCountryValue) && !empty($attributeCountryTitle)) :?>
        
      <td class="td_first">
        <?= /* @noEscape */  $attributeCountryTitle; ?>
      </td>
      <td>
        <?= /* @noEscape */  $attributeCountryValue; ?>
      </td>
    <?php endif; ?>
    </tr>
  </tbody>
</table>
</div>
</div>
<?php endif; ?>

