<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $_helperB2b = $this->helper(Alfakher\Productpageb2b\Helper\Data::class); ?>
<?php if ($_helperB2b->isCustomerLoggedIn()): ?>
    <?php if ($_product->isSaleable()):?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()):?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <?php
                $userAgent = $block->getRequest()->getHeader('useragent');
                $server    = $block->getRequest()->getServer();

                $isMobileDevice = \Zend_Http_UserAgent_Mobile::match($userAgent, $server);
                $isDesktopDevice = \Zend_Http_UserAgent_Desktop::match($userAgent, $server);
                if (!$isDesktopDevice):
                    //Write your code here for Mobile view
                    $qtyCounter=$block->getProductDefaultQty() * 1 ;
                    $dataValidate=json_encode($block->getQuantityValidators());
                    ?>
                    <select 
                        class="input-text qty" 
                        name="qty" 
                        id="qty" 
                        data-validate="<?= /* @noEscape */ $block->escapeHtml($dataValidate) ?>">
                        <?php for ($qtyCounter; $qtyCounter<=100; $qtyCounter++):
                            $selected='';
                            if (($block->getProductDefaultQty() * 1) == $qtyCounter):
                                $selected='selected';
                            endif; ?>
                            <option value="<?= /* @noEscape */ $qtyCounter; ?>"
                                <?= /* @noEscape */  $selected; ?>>
                                <?= /* @noEscape */ $qtyCounter; ?>
                            </option>
                        <?php endfor; ?>
                    </select> 
                    <?php else:
                        $dataValidate=json_encode($block->getQuantityValidators());
                        ?>
                
                 <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= /* @noEscape */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= /* @noEscape */ $block->escapeHtml($dataValidate) ?>"
                       /> 
                  <?php endif; ?>  
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
                <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
    <?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php else:?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?php $loginUrl=$block->getUrl('customer/account/login');
            $creatUrl=$block->getUrl('customer/account/create'); ?>
            <?= $block->escapeHtml(
                __('Only registered users can see the price. 
                    Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $loginUrl, $creatUrl),
                ['a']
            )
            ?>
        </div>
    </div>
<?php endif;?>
